#------------------------------------------------------------------------------
# FILE:         action.yaml
# CONTRIBUTOR:  Jeff Lill
# COPYRIGHT:    Copyright (c) 2005-2021 by neonFORGE LLC.  All rights reserved.
#
# The contents of this repository are for private use by neonFORGE, LLC. and may not be
# divulged or used for any purpose by other organizations or individuals without a
# formal written and signed agreement with neonFORGE, LLC.

#------------------------------------------------------------------------------
# Clears the runner state including:
#
#   * clearing the GITHUB_WORKSPACE directory
#   * clearing the TMP directory
#   * stopping any removing any Hype-V VMs
#
# NOTE: You must run the [setup-node] action before this to ensure that
#       Node.js is configured on the runner.

name: clean
description: "Clears the runner state including the GITHUB_WORKSPACE directory"
inputs:
  default:
    description: "The default value for the remaining options"
    required: false
    default: "true"
  workspace:
    description: "Clears the GitHub runner's workspace folder"
    required: false
  builds:
    description: "Clears the bin/obj folders for the solutions"
    required: false
  hyperv:
    description: "Stops and deletes any hyper-v VMs"
    required: false
  xenserver:
    description: "Stops and deletes any xenserver VMs"
    required: false
  containers:
    description: "Prunes all Docker assets including containers and images"
    required: false
  wsl:
    description: "Removes all WSL distributions except for those belonging to Docker"
    required: false
  nuget:
    description: "Clears the nuget package caches"
    required: false
  neonkube:
    description: "Clears the user's [.neonkube] folder"
    required: false
  tmp:
    description: "Clears the TMP folder"
    required: false
  pwsh-history:
    description: "Clears the Powershell command history"
    required: false
runs:
  using: node12
  main: action.js
